provider: virtualbox
mgmt01: "{{ hostvars['mgmt01'].ansible_host }}"
tower01: "{{ hostvars['tower01'].ansible_host }}"
server01: "{{ hostvars['server01'].ansible_host }}"
server02: "{{ hostvars['server02'].ansible_host }}"
spine01: "{{ hostvars['spine01'].ansible_host }}"
spine02: "{{ hostvars['spine02'].ansible_host }}"
leaf01: "{{ hostvars['leaf01'].ansible_host }}"
leaf02: "{{ hostvars['leaf02'].ansible_host }}"
leaf03: "{{ hostvars['leaf03'].ansible_host }}"
leaf04: "{{ hostvars['leaf04'].ansible_host }}"
