---
dependencies:
  - topology

galaxy_info:
  author: victorock
  description: Cisco NXOS Topology Builder
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: NXOS
    versions:
    - all
  galaxy_tags:
    - network
