---
- name: "Topology"
  fail:
    msg: |
      The following devices are available:
        0- none (destroy everything)
        1- tower01
        2- mgmt01
        3- server01
        4- server02

      Follow below few examples showing how to chose your topology:
        -e device=1
        -e topology=2
        -e topology=2s2l
        -e topology=2s3l
        -e topology=5

      In order to destroy the topology:
        -e topology=0

  when:
    - device is not defined
    - devices is not defined

- name: "Start Device"
  block:
    - name: "Device spine01"
      command:
        vagrant up {{ item | quote }}
      args:
        chdir: files
        creates:
          - ".vagrant/machines/{{ item }}/virtualbox/id"
      when:
        - ( device == 'spine01' ) or ( device == '11' )
      with_items:
        - spine01

    - name: "Device spine02"
      command:
        vagrant up {{ item | quote }}
      args:
        chdir: files
        creates:
          - ".vagrant/machines/{{ item }}/virtualbox/id"
      when:
        - ( device == 'spine02' ) or ( device == '12' )
      with_items:
        - spine02

    - name: "Device leaf01"
      command:
        vagrant up {{ item | quote }}
      args:
        chdir: files
        creates:
          - ".vagrant/machines/{{ item }}/virtualbox/id"
      when:
        - ( device == 'leaf01' ) or ( device == '21' )
      with_items:
        - leaf01

    - name: "Device leaf02"
      command:
        vagrant up {{ item | quote }}
      args:
        chdir: files
        creates:
          - ".vagrant/machines/{{ item }}/virtualbox/id"
      when:
        - ( device == 'leaf02' ) or ( device == '22' )
      with_items:
        - leaf02

    - name: "Device leaf03"
      command:
        vagrant up {{ item | quote }}
      args:
        chdir: files
        creates:
          - ".vagrant/machines/{{ item }}/virtualbox/id"
      when:
        - ( device == 'leaf03' ) or ( device == '23' )
      with_items:
        - leaf03

    - name: "Device leaf04"
      command:
        vagrant up {{ item | quote }}
      args:
        chdir: files
        creates:
          - ".vagrant/machines/{{ item }}/virtualbox/id"
      when:
        - ( device == 'leaf04' ) or ( device == '24' )
      with_items:
        - leaf04

  when: device is defined
