#!/usr/bin/env ansible-playbook
---
- name: "Topology Configuration"
  hosts: control,server
  gather_facts: yes
  become: yes

  tasks:
    - name: "Configure Topology"
      include_role:
        name: vagrant-base
